name = "gns"
main = "index.py"
compatibility_date = "2024-05-01"
compatibility_flags = ["python_workers"]

# 1분마다 실행되는 스케줄러 설정
[triggers]
crons = ["* * * * *"]

# 데이터 저장소(KV) 바인딩
[[kv_namespaces]]
binding = "NEWS_KV"
id = "1700ec2f6e1b4fd2aeafca587d2156ee"
